[tool.poetry]
name = "ted-z"
version = "0.1.0"
description = "Just another Discord bot written in Python! (this is the last revision i swear)"
authors = ["Alex The JPEG <alexthejpeg@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
hikari-crescent = "^0.3.5"
tomli = "^2.0.1"
goslate = "^1.5.4"
requests = "^2.28.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
